import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://tyiecstaywsocmqsabhg.supabase.co';
const supabaseKey = 'sb_publishable_02kGJR-DB9gOz0RGANer7A_aygtlC64';

const supabase = createClient(supabaseUrl, supabaseKey);

async function seedDatabase() {
  console.log('🚀 Starting Supabase Database Seeding...');

  // 1. Communities
  console.log('Seeding communities...');
  const { error: commErr } = await supabase.from('communities').upsert([
    {
      id: 'comm_bareilly_hq',
      name: 'Bareilly Central Care Society (Headquarters)',
      city: 'Bareilly',
      state: 'Uttar Pradesh',
      admin_name: 'Maulana Hafiz Ziauddin Bareillvi',
      admin_role_title: 'Headquarters Administrator',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
      total_members: 3450,
      active_campaigns: 12,
      total_raised_inr: 9850000,
      health_score: 99,
      verified_status: 'Verified',
      description: 'Headquarters of SevaSangam in Civil Lines, Bareilly. Managing emergency Janazah mortuary van, Nikah bridal kits, and student scholarships across Uttar Pradesh.',
      established_year: 2017,
      cover_image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'comm_bareilly_rohilkhand',
      name: 'Rohilkhand Educational & Nikah Trust',
      city: 'Bareilly',
      state: 'Uttar Pradesh',
      admin_name: 'Dr. Shakeel Ahmad Usmani',
      admin_role_title: 'Community Administrator',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      total_members: 1820,
      active_campaigns: 5,
      total_raised_inr: 4120000,
      health_score: 97,
      verified_status: 'Verified',
      description: 'Serving Qutubkhana and Rohilkhand University area through collective Nikah assistance, widow pensions, and orphan schooling.',
      established_year: 2019,
      cover_image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'comm_lko_chowk',
      name: 'Chowk Heritage Community Foundation',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      admin_name: 'Syed Tariq Husain',
      admin_role_title: 'Community Administrator',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      total_members: 1190,
      active_campaigns: 4,
      total_raised_inr: 3290000,
      health_score: 95,
      verified_status: 'Verified',
      description: 'Focusing on girl-child higher education, artisan medical aid, and emergency heart surgeries in Lucknow & Central UP.',
      established_year: 2020,
      cover_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'comm_delhi_central',
      name: 'Hazrat Nizamuddin Welfare Community',
      city: 'Delhi',
      state: 'Delhi NCR',
      admin_name: 'Maulana Salman Farooqui',
      admin_role_title: 'Community Administrator',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      total_members: 1240,
      active_campaigns: 6,
      total_raised_inr: 4250000,
      health_score: 98,
      verified_status: 'Verified',
      description: 'Providing medical, educational, and monthly food kit assistance to lower-income North Indian families in Central Delhi.',
      established_year: 2018,
      cover_image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'comm_bareilly_izatnagar',
      name: 'Izatnagar & CB Ganj Care Society',
      city: 'Bareilly',
      state: 'Uttar Pradesh',
      admin_name: 'Alhaj Mohammad Yusuf',
      admin_role_title: 'Community Administrator',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
      total_members: 980,
      active_campaigns: 4,
      total_raised_inr: 2150000,
      health_score: 94,
      verified_status: 'Verified',
      description: 'Operating free ambulance transfers, winter clothing drives, and skill development for youth in Izatnagar & CB Ganj Bareilly.',
      established_year: 2021,
      cover_image: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80',
    },
  ]);
  if (commErr) console.error('Error seeding communities:', commErr.message);

  // 2. Users
  console.log('Seeding users...');
  const { error: userErr } = await supabase.from('users').upsert([
    {
      id: 'usr_mem_101',
      name: 'Aarif Khan',
      email: 'aarif.khan@example.com',
      phone: '+91 98765 43210',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      community_id: 'comm_delhi_central',
      community_name: 'Hazrat Nizamuddin Welfare Community',
      membership_id: 'SS-DEL-2024-8842',
      is_verified: true,
      is_premium: false,
      join_date: '12 Jan 2024',
      city: 'Delhi',
      state: 'Delhi NCR',
      total_donated_inr: 12500,
      donations_count: 14,
    },
    {
      id: 'usr_prem_202',
      name: 'Ayesha Fatima',
      email: 'ayesha.fatima@example.com',
      phone: '+91 98112 33445',
      role: 'premium_donor',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
      community_id: 'comm_bareilly_rohilkhand',
      community_name: 'Rohilkhand Educational & Nikah Trust',
      membership_id: 'SS-HYD-PREM-0012',
      is_verified: true,
      is_premium: true,
      join_date: '04 Mar 2023',
      city: 'Hyderabad',
      state: 'Telangana',
      total_donated_inr: 185000,
      donations_count: 48,
      life_impact_score: 94,
      families_helped: 38,
      hasanat_counter: 14850,
      giving_streak_months: 18,
      community_rank: 3,
    },
    {
      id: 'usr_mem_103',
      name: 'Mohammad Tariq',
      email: 'tariq@example.com',
      phone: '+91 98220 11223',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      community_id: 'comm_bareilly_rohilkhand',
      community_name: 'Charminar Heritage & Care Society',
      membership_id: 'SS-HYD-2024-1042',
      is_verified: true,
      is_premium: false,
      join_date: '15 Feb 2024',
      city: 'Hyderabad',
      state: 'Telangana',
      total_donated_inr: 8500,
      donations_count: 8,
    },
    {
      id: 'usr_mem_104',
      name: 'Syeda Saira Begum',
      email: 'saira@example.com',
      phone: '+91 97110 55443',
      role: 'member',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      community_id: 'comm_bareilly_rohilkhand',
      community_name: 'Kurla Progressive Community Care',
      membership_id: 'SS-MUM-2024-0092',
      is_verified: true,
      is_premium: false,
      join_date: '01 Mar 2024',
      city: 'Mumbai',
      state: 'Maharashtra',
      total_donated_inr: 14000,
      donations_count: 11,
    },
  ]);
  if (userErr) console.error('Error seeding users:', userErr.message);

  // 3. Campaigns
  console.log('Seeding campaigns...');
  const { error: campErr } = await supabase.from('campaigns').upsert([
    {
      id: 'camp_med_01',
      title: 'Urgent Kidney Transplant for 8-Year-Old Zoya in AIIMS Delhi',
      slug: 'kidney-transplant-zoya-aiims',
      category: 'Medical',
      community_id: 'comm_delhi_central',
      community_name: 'Hazrat Nizamuddin Welfare Community',
      city: 'Delhi',
      beneficiary_name: 'Zoya Siddiqui (8 yrs)',
      beneficiary_relation: 'Father: Imran Siddiqui (Daily wage carpenter)',
      goal_inr: 450000,
      raised_inr: 320000,
      donors_count: 184,
      days_left: 8,
      is_verified: true,
      is_zakat_eligible: true,
      is_urgent: true,
      is_premium_featured: true,
      main_image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80',
      story: 'Little Zoya was diagnosed with end-stage renal disease 4 months ago. Her father works as a local daily-wage wood craftsman and has exhausted all savings on weekly dialysis.',
      documents: [
        { title: 'AIIMS Medical Prescription & Estimate', url: '#', verifiedBy: 'Executive Team' },
        { title: 'Aadhaar Card & Income Certificate', url: '#', verifiedBy: 'Community Admin' },
      ],
      verification_timeline: [
        { step: 'Beneficiary Identity Verification', date: '10 Jul 2024', status: 'completed' },
        { step: 'Medical Hospital On-site Verification', date: '12 Jul 2024', status: 'completed' },
        { step: 'Executive Committee Approval', date: '14 Jul 2024', status: 'completed' },
        { step: 'Campaign Live & Direct Bank Escrow Active', date: '15 Jul 2024', status: 'completed' },
      ],
      need_breakdown: [
        { item: 'Surgery & Operation Theatre Charges', amountINR: 220000 },
        { item: 'ICU Stay & Monitoring (10 Days)', amountINR: 110000 },
        { item: 'Post-transplant Immunosuppressant Medications', amountINR: 80000 },
        { item: 'Blood Transfusion & Pre-op Testing', amountINR: 40000 },
      ],
      created_date: '15 Jul 2024',
      status: 'active',
    },
    {
      id: 'camp_edu_02',
      title: 'Higher Education Scholarship Fund for 15 Orphan Girls in Bareilly',
      slug: 'orphan-girls-higher-education-bareilly',
      category: 'Education',
      community_id: 'comm_bareilly_rohilkhand',
      community_name: 'Bareilly Unity & Relief Council',
      city: 'Bareilly',
      beneficiary_name: '15 Student Scholars',
      beneficiary_relation: 'Care of Bareilly Orphan Care Trust',
      goal_inr: 300000,
      raised_inr: 215000,
      donors_count: 96,
      days_left: 14,
      is_verified: true,
      is_zakat_eligible: true,
      is_urgent: false,
      is_premium_featured: true,
      main_image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
      story: '15 bright young girls who cleared their Class 12 exams with top honors (above 85%) lack the financial means to pay college admission fees.',
      documents: [{ title: 'Mark Sheets & College Admission Letters', url: '#', verifiedBy: 'Executive Team' }],
      verification_timeline: [
        { step: 'Academic Verification', date: '01 Jun 2024', status: 'completed' },
        { step: 'College Fee Structure Clearance', date: '05 Jun 2024', status: 'completed' },
      ],
      need_breakdown: [
        { item: 'College Admission & Semester Fees (15 students)', amountINR: 210000 },
        { item: 'Books, Uniforms & Study Kit', amountINR: 60000 },
        { item: 'Transport Stipend', amountINR: 30000 },
      ],
      created_date: '10 Jun 2024',
      status: 'active',
    },
    {
      id: 'camp_marr_03',
      title: 'Simple Dignified Marriage Support for Orphan Bride Sania in Lucknow',
      slug: 'marriage-support-sania-lucknow',
      category: 'Marriage',
      community_id: 'comm_lko_chowk',
      community_name: 'Chowk Heritage Community Foundation',
      city: 'Lucknow',
      beneficiary_name: 'Sania Parveen (21 yrs)',
      beneficiary_relation: 'Mother: Rashida Begum (Widow)',
      goal_inr: 120000,
      raised_inr: 98000,
      donors_count: 64,
      days_left: 5,
      is_verified: true,
      is_zakat_eligible: true,
      is_urgent: true,
      is_premium_featured: false,
      main_image: 'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=800&q=80',
      story: 'Sania lost her father 6 years ago. Her widowed mother works hard stitching clothes to feed her family.',
      documents: [{ title: 'Nikah Registration Card & Invitation', url: '#', verifiedBy: 'Community Admin' }],
      verification_timeline: [
        { step: 'Local Verification & Community Visit', date: '18 Jul 2024', status: 'completed' },
      ],
      need_breakdown: [
        { item: 'Basic Household Essentials & Sewing Machine Gift', amountINR: 75000 },
        { item: 'Simple Meal & Venue Arrangement for 40 Guests', amountINR: 35000 },
      ],
      created_date: '20 Jul 2024',
      status: 'active',
    },
    {
      id: 'camp_food_04',
      title: 'Monthly Ration Kits for 200 Flood Affected Families in Hyderabad',
      slug: 'monthly-ration-kits-hyderabad',
      category: 'Food',
      community_id: 'comm_bareilly_rohilkhand',
      community_name: 'Charminar Heritage & Care Society',
      city: 'Hyderabad',
      beneficiary_name: '200 Lower-income Families',
      beneficiary_relation: 'Old City Flood Relief Drive',
      goal_inr: 500000,
      raised_inr: 410000,
      donors_count: 230,
      days_left: 12,
      is_verified: true,
      is_zakat_eligible: true,
      is_urgent: true,
      is_premium_featured: true,
      main_image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80',
      story: 'Heavy monsoon rains flooded low-lying streets in Hyderabad, damaging food stocks and homes of informal daily wage workers.',
      documents: [{ title: 'Beneficiary List & Token Verification', url: '#', verifiedBy: 'Community Admin' }],
      verification_timeline: [
        { step: 'Survey of Affected Households', date: '02 Jul 2024', status: 'completed' },
      ],
      need_breakdown: [
        { item: '200 Ration Grocery Bags @ ₹2200 per bag', amountINR: 440000 },
        { item: 'Packing & Transportation Logistics', amountINR: 60000 },
      ],
      created_date: '05 Jul 2024',
      status: 'active',
    },
    {
      id: 'camp_jan_07',
      title: 'Janazah Funeral Emergency Fund & Cemetery Ambulance Support',
      slug: 'janazah-emergency-funeral-fund',
      category: 'Janazah',
      community_id: 'comm_lko_chowk',
      community_name: 'Chowk Heritage Community Foundation',
      city: 'Lucknow',
      beneficiary_name: 'Destitute & Unclaimed Janazah Service',
      beneficiary_relation: 'Community Welfare Services',
      goal_inr: 150000,
      raised_inr: 112000,
      donors_count: 88,
      days_left: 18,
      is_verified: true,
      is_zakat_eligible: true,
      is_urgent: true,
      is_premium_featured: false,
      main_image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
      story: 'Ensuring dignified final rites, Kafan burial cloth, mortuary van transportation, and cemetery grave preparation for impoverished families.',
      documents: [{ title: 'Community Funeral Welfare Audit Report', url: '#', verifiedBy: 'Executive Team' }],
      verification_timeline: [
        { step: 'Cemetery Committee Authorization', date: '01 Jul 2024', status: 'completed' },
      ],
      need_breakdown: [
        { item: 'Kafan, Ghusl & Burial Materials (20 services)', amountINR: 70000 },
        { item: 'Mortuary Van Maintenance & Fuel', amountINR: 50000 },
      ],
      created_date: '01 Jul 2024',
      status: 'active',
    },
  ]);
  if (campErr) console.error('Error seeding campaigns:', campErr.message);

  // 4. Donations
  console.log('Seeding donations...');
  const { error: donErr } = await supabase.from('donations').upsert([
    {
      id: 'don_801',
      transaction_id: 'TXN998241029',
      utr_number: '420199381029',
      donor_name: 'Rahul Sharma',
      donor_id: 'usr_mem_101',
      donor_role: 'member',
      campaign_id: 'camp_med_01',
      campaign_title: 'Urgent Kidney Transplant for 8-Year-Old Zoya in AIIMS Delhi',
      community_name: 'Hazrat Nizamuddin Welfare Community',
      amount_inr: 2500,
      category: 'Zakat',
      is_outside_community: false,
      payment_method: 'UPI',
      status: 'verified',
      date: '28 Jul 2024, 02:45 PM',
      receipt_number: 'RCP-2024-0982',
    },
    {
      id: 'don_802',
      transaction_id: 'TXN998241030',
      utr_number: '420199381030',
      donor_name: 'Ayesha Fatima',
      donor_id: 'usr_prem_202',
      donor_role: 'premium_donor',
      campaign_id: 'camp_edu_02',
      campaign_title: 'Higher Education Scholarship Fund for 15 Orphan Girls',
      community_name: 'Bareilly Unity & Relief Council',
      amount_inr: 10000,
      category: 'Sadakah',
      is_outside_community: true,
      payment_method: 'UPI',
      status: 'verified',
      date: '27 Jul 2024, 11:15 AM',
      receipt_number: 'RCP-2024-0983',
    },
    {
      id: 'don_803',
      transaction_id: 'TXN998241031',
      utr_number: '420199381031',
      donor_name: 'Sneha Gupta',
      donor_id: 'usr_mem_103',
      donor_role: 'member',
      campaign_id: 'camp_food_04',
      campaign_title: 'Monthly Ration Kits for 200 Flood Affected Families',
      community_name: 'Charminar Heritage & Care Society',
      amount_inr: 1000,
      category: 'General',
      is_outside_community: true,
      payment_method: 'QR Code',
      status: 'verified',
      date: '26 Jul 2024, 06:20 PM',
      receipt_number: 'RCP-2024-0984',
    },
    {
      id: 'don_804',
      transaction_id: 'TXN998241032',
      utr_number: '420199381032',
      donor_name: 'Mohammed Sameer',
      donor_id: 'usr_mem_104',
      donor_role: 'member',
      campaign_id: 'camp_marr_03',
      campaign_title: 'Simple Dignified Marriage Support for Orphan Bride Sania',
      community_name: 'Chowk Heritage Community Foundation',
      amount_inr: 5000,
      category: 'Zakat',
      is_outside_community: false,
      payment_method: 'Bank Transfer',
      status: 'verified',
      date: '25 Jul 2024, 10:05 AM',
      receipt_number: 'RCP-2024-0985',
    },
  ]);
  if (donErr) console.error('Error seeding donations:', donErr.message);

  // 5. Testimonials
  console.log('Seeding testimonials...');
  const { error: testErr } = await supabase.from('testimonials').upsert([
    {
      id: 'test_01',
      name: 'Imran Siddiqui',
      role: 'Beneficiary Father',
      city: 'Delhi',
      quote: 'When my daughter Zoya needed an emergency kidney transplant, our local SevaSangam community raised ₹3.2 Lakhs in under two weeks. The transparency and direct hospital payments gave us hope.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      campaign_title: 'Urgent Kidney Transplant for Zoya',
      amount_received_inr: 320000,
    },
    {
      id: 'test_02',
      name: 'Rashida Begum',
      role: 'Widow Mother',
      city: 'Lucknow',
      quote: 'As a single mother working on daily stitching wages, I could never have arranged my daughter Sania\'s wedding essentials without the community\'s ₹50 membership solidarity.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      campaign_title: 'Marriage Support for Orphan Bride Sania',
      amount_received_inr: 98000,
    },
    {
      id: 'test_03',
      name: 'Dr. Mohammed Ahmed',
      role: 'Community Admin',
      city: 'Hyderabad',
      quote: 'Managing 2,000+ local families through SevaSangam has completely eliminated fraud. Every rupee donated inside or outside our community is tracked with clear UTR receipts.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    },
  ]);
  if (testErr) console.error('Error seeding testimonials:', testErr.message);

  // 6. Community Stories
  console.log('Seeding community stories...');
  const { error: storyErr } = await supabase.from('community_stories').upsert([
    {
      id: 'story_01',
      title: 'How 1,200 Delhi Families Provided 3,000 Fresh Warm Meals During Cold Waves',
      category: 'Emergency Relief',
      location: 'Nizamuddin, Delhi',
      date: '15 Jan 2024',
      image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=600&q=80',
      summary: 'A 10-day emergency drive mobilized local volunteers to serve hot nutritious food and distribute woolens to homeless elderly residents.',
      impact_metric: '3,000 Hot Meals & 500 Blankets',
    },
    {
      id: 'story_02',
      title: 'Zero Drop-out Rate: Bareilly Girls Achieve 100% High School Graduation',
      category: 'Education',
      location: 'Bareilly, Uttar Pradesh',
      date: '02 Apr 2024',
      image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80',
      summary: 'Through micro-sponsorships of ₹50/month per member, 45 young girls completed their secondary school education and enrolled in degree colleges.',
      impact_metric: '45 Girls Higher Enrolled',
    },
  ]);
  if (storyErr) console.error('Error seeding stories:', storyErr.message);

  // 7. Gallery Photos
  console.log('Seeding gallery photos...');
  const { error: galErr } = await supabase.from('gallery_photos').upsert([
    {
      title: 'Dignified Nikah Essentials & Bridal Trunk Drive - Qutubkhana, Bareilly (UP)',
      city: 'Bareilly',
      image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
      category: 'Nikah Support',
    },
    {
      title: 'Schooling Kit & Book Distribution for Orphan Girls - Bareilly (UP)',
      city: 'Bareilly',
      image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=600&q=80',
      category: 'Child Education',
    },
    {
      title: 'Emergency Medical & Dialysis Consultation Drive - Bareilly District Hospital',
      city: 'Bareilly',
      image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
      category: 'Medical Aid',
    },
    {
      title: 'Monthly Food Grocery Ration Kits Distribution - CB Ganj, Bareilly',
      city: 'Bareilly',
      image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80',
      category: 'Food Relief',
    },
  ]);
  if (galErr) console.error('Error seeding gallery:', galErr.message);

  // 8. User Badges & Monthly Stats
  console.log('Seeding user badges & stats...');
  const { error: badgeErr } = await supabase.from('user_badges').upsert([
    {
      id: 'bdg_01',
      user_id: 'usr_prem_202',
      badge_name: 'Grand Patron Award 2024',
      badge_description: 'Contributed over ₹1.5 Lakhs in a year',
      badge_type: 'gold',
    },
    {
      id: 'bdg_02',
      user_id: 'usr_prem_202',
      badge_name: 'Lifesaver Medical Shield',
      badge_description: 'Funded 3 emergency heart/kidney surgeries',
      badge_type: 'emerald',
    },
    {
      id: 'bdg_03',
      user_id: 'usr_prem_202',
      badge_name: 'Education Guardian',
      badge_description: 'Sponsored higher studies for 8 orphan girls',
      badge_type: 'blue',
    },
  ]);
  if (badgeErr) console.error('Error seeding user badges:', badgeErr.message);

  const { error: statErr } = await supabase.from('monthly_donation_stats').upsert([
    { user_id: 'usr_prem_202', month: 'Jan', year: 2024, amount_inr: 15000 },
    { user_id: 'usr_prem_202', month: 'Feb', year: 2024, amount_inr: 18000 },
    { user_id: 'usr_prem_202', month: 'Mar', year: 2024, amount_inr: 12000 },
    { user_id: 'usr_prem_202', month: 'Apr', year: 2024, amount_inr: 25000 },
    { user_id: 'usr_prem_202', month: 'May', year: 2024, amount_inr: 30000 },
    { user_id: 'usr_prem_202', month: 'Jun', year: 2024, amount_inr: 40000 },
    { user_id: 'usr_prem_202', month: 'Jul', year: 2024, amount_inr: 45000 },
  ]);
  if (statErr) console.error('Error seeding monthly stats:', statErr.message);

  // 9. Pending Verifications & Audit Logs
  console.log('Seeding pending verifications & audit logs...');
  const { error: verErr } = await supabase.from('pending_verifications').upsert([
    {
      id: 'ver_kyc_01',
      type: 'kyc',
      title: 'New Member Membership Verification - Bareilly Community',
      submitted_by: 'Vikram Malhotra (+91 98123 77665)',
      date: 'Today, 04:12 PM',
      status: 'pending',
      details: 'Aadhaar ID matched. Paid ₹50 membership fee. Pending Executive signature.',
      document_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    },
    {
      id: 'ver_camp_02',
      type: 'campaign',
      title: 'New Medical Campaign: Heart Valve Surgery for 12yo Ananya',
      submitted_by: 'Dr. Mohammed Ahmed (Community Admin)',
      date: 'Today, 02:00 PM',
      status: 'pending',
      details: 'Requested ₹3.2 Lakhs goal. Hospital estimation document attached.',
      document_url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=300&q=80',
      amount_inr: 320000,
    },
  ]);
  if (verErr) console.error('Error seeding pending verifications:', verErr.message);

  const { error: logErr } = await supabase.from('audit_logs').upsert([
    {
      id: 'log_01',
      timestamp: '29 Jul 2024 05:45 PM',
      action: 'Campaign Approved',
      performed_by: 'Executive Team (Farhan Ali)',
      role: 'executive',
      details: 'Verified AIIMS Hospital estimate for Campaign #camp_med_01. Escrow enabled.',
      ip_address: '103.22.45.12',
    },
    {
      id: 'log_02',
      timestamp: '29 Jul 2024 03:20 PM',
      action: 'KYC Verified & Receipt Issued',
      performed_by: 'Executive Team (Farhan Ali)',
      role: 'executive',
      details: 'Verified Aadhaar KYC for Member #SS-DEL-2024-8842.',
      ip_address: '103.22.45.12',
    },
  ]);
  if (logErr) console.error('Error seeding audit logs:', logErr.message);

  console.log('✅ Supabase Seeding Complete!');
}

seedDatabase().catch((e) => console.error('Seeding process failed:', e));
