-- ==============================================================================
-- SQL to Create 'district_teams' & 'meeting' Tables in Supabase (PUBLIC Schema)
-- Run this in your Supabase Project -> SQL Editor -> Run
-- ==============================================================================

-- 1. Ensure public schema permissions for API roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;


-- 2. Create 'district_teams' table in 'public' schema
CREATE TABLE IF NOT EXISTS public.district_teams (
  id TEXT PRIMARY KEY DEFAULT ('team-' || floor(extract(epoch from now()) * 1000)::text),
  unit_name TEXT NOT NULL,
  tehsil_or_zone TEXT DEFAULT '',
  district TEXT DEFAULT '',
  head_name TEXT DEFAULT '',
  head_phone TEXT DEFAULT '',
  president_name TEXT DEFAULT '',
  president_phone TEXT DEFAULT '',
  secretary_name TEXT DEFAULT '',
  secretary_phone TEXT DEFAULT '',
  coordinator_name TEXT DEFAULT '',
  coordinator_phone TEXT DEFAULT '',
  unit_type TEXT DEFAULT 'block',
  formed_date TEXT DEFAULT '',
  active_volunteers_count INTEGER DEFAULT 15,
  status TEXT DEFAULT 'pending',
  objectives TEXT DEFAULT '',
  members JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure all columns exist in public.district_teams
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS head_name TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS head_phone TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS president_name TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS president_phone TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS secretary_name TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS secretary_phone TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS coordinator_name TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS coordinator_phone TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS unit_type TEXT DEFAULT 'block';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS tehsil_or_zone TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS district TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS formed_date TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS active_volunteers_count INTEGER DEFAULT 15;
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS objectives TEXT DEFAULT '';
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS members JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.district_teams ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Enable RLS and create full access policies for public.district_teams
ALTER TABLE public.district_teams ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read district_teams" ON public.district_teams;
CREATE POLICY "Allow public read district_teams" ON public.district_teams FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert district_teams" ON public.district_teams;
CREATE POLICY "Allow insert district_teams" ON public.district_teams FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update district_teams" ON public.district_teams;
CREATE POLICY "Allow update district_teams" ON public.district_teams FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete district_teams" ON public.district_teams;
CREATE POLICY "Allow delete district_teams" ON public.district_teams FOR DELETE USING (true);

-- Alias table public.teams
CREATE TABLE IF NOT EXISTS public.teams (LIKE public.district_teams INCLUDING ALL);
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read teams" ON public.teams;
CREATE POLICY "Allow public read teams" ON public.teams FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert teams" ON public.teams;
CREATE POLICY "Allow insert teams" ON public.teams FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update teams" ON public.teams;
CREATE POLICY "Allow update teams" ON public.teams FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete teams" ON public.teams;
CREATE POLICY "Allow delete teams" ON public.teams FOR DELETE USING (true);


-- 3. Create 'meeting' table in 'public' schema
CREATE TABLE IF NOT EXISTS public.meeting (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  agenda TEXT DEFAULT '',
  date TEXT NOT NULL,
  time TEXT NOT NULL DEFAULT '11:00 AM - 01:00 PM',
  venue TEXT DEFAULT '',
  chairperson TEXT DEFAULT 'District President',
  recorded_by TEXT DEFAULT 'District Secretary',
  attendees_count INTEGER DEFAULT 10,
  status TEXT DEFAULT 'upcoming',
  district TEXT DEFAULT '',
  minutes TEXT DEFAULT '',
  resolutions JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure all columns exist on public.meeting
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS agenda TEXT DEFAULT '';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS time TEXT DEFAULT '11:00 AM - 01:00 PM';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS venue TEXT DEFAULT '';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS chairperson TEXT DEFAULT 'District President';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS recorded_by TEXT DEFAULT 'District Secretary';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS attendees_count INTEGER DEFAULT 10;
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'upcoming';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS district TEXT DEFAULT '';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS minutes TEXT DEFAULT '';
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS resolutions JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.meeting ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.meeting ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read meeting" ON public.meeting;
CREATE POLICY "Allow public read meeting" ON public.meeting FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert meeting" ON public.meeting;
CREATE POLICY "Allow insert meeting" ON public.meeting FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update meeting" ON public.meeting;
CREATE POLICY "Allow update meeting" ON public.meeting FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete meeting" ON public.meeting;
CREATE POLICY "Allow delete meeting" ON public.meeting FOR DELETE USING (true);

-- Alias tables public.meetings and public.district_meetings
CREATE TABLE IF NOT EXISTS public.meetings (LIKE public.meeting INCLUDING ALL);
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read meetings" ON public.meetings;
CREATE POLICY "Allow public read meetings" ON public.meetings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert meetings" ON public.meetings;
CREATE POLICY "Allow insert meetings" ON public.meetings FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update meetings" ON public.meetings;
CREATE POLICY "Allow update meetings" ON public.meetings FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete meetings" ON public.meetings;
CREATE POLICY "Allow delete meetings" ON public.meetings FOR DELETE USING (true);

CREATE TABLE IF NOT EXISTS public.district_meetings (LIKE public.meeting INCLUDING ALL);
ALTER TABLE public.district_meetings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read district_meetings" ON public.district_meetings;
CREATE POLICY "Allow public read district_meetings" ON public.district_meetings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert district_meetings" ON public.district_meetings;
CREATE POLICY "Allow insert district_meetings" ON public.district_meetings FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update district_meetings" ON public.district_meetings;
CREATE POLICY "Allow update district_meetings" ON public.district_meetings FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete district_meetings" ON public.district_meetings;
CREATE POLICY "Allow delete district_meetings" ON public.district_meetings FOR DELETE USING (true);


-- 4. MIGRATE EXISTING ROWS FROM 'dev' TO 'public' (Matches EXACT dev columns)
DO $$
BEGIN
  -- Copy teams from dev.district_teams using ONLY columns that exist in dev
  IF EXISTS (
    SELECT FROM information_schema.tables
    WHERE table_schema = 'dev' AND table_name = 'district_teams'
  ) THEN
    INSERT INTO public.district_teams (
      id,
      unit_name,
      tehsil_or_zone,
      district,
      head_name,
      head_phone,
      president_name,
      president_phone,
      formed_date,
      active_volunteers_count,
      status,
      objectives,
      members,
      created_at,
      updated_at
    )
    SELECT
      id,
      unit_name,
      tehsil_or_zone,
      district,
      head_name,
      head_phone,
      head_name,
      head_phone,
      formed_date,
      active_volunteers_count,
      status,
      objectives,
      CASE
        WHEN members IS NULL THEN '[]'::jsonb
        ELSE members::text::jsonb
      END,
      created_at,
      updated_at
    FROM dev.district_teams
    ON CONFLICT (id) DO NOTHING;
  END IF;

  -- Copy meetings from dev.meeting using ONLY columns that exist in dev
  IF EXISTS (
    SELECT FROM information_schema.tables
    WHERE table_schema = 'dev' AND table_name = 'meeting'
  ) THEN
    INSERT INTO public.meeting (
      id,
      title,
      agenda,
      date,
      time,
      venue,
      recorded_by,
      status,
      district,
      created_at,
      updated_at
    )
    SELECT
      id,
      title,
      agenda,
      date,
      time,
      venue,
      recorded_by,
      status,
      district,
      created_at,
      updated_at
    FROM dev.meeting
    ON CONFLICT (id) DO NOTHING;

    -- Sync auto-increment sequence with highest ID copied
    PERFORM setval(
      pg_get_serial_sequence('public.meeting', 'id'),
      COALESCE((SELECT MAX(id) FROM public.meeting), 1)
    );
  END IF;
END $$;


-- 5. Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
